#!/bin/bash

# Global.
ret=0

# These are probably worth alerting on.  More cautious numbers would probably be machine specific.
critical_low=10
warning_low=20
warning_high=70
critical_high=80

# Other settings.
interval=1
shopt -s nullglob

function main() {
  cd /sys/class/thermal/

  # zone_temps is an array of strings; each string is a space separated series of temperatures.
  zone_temps=()
  # zone_types is an array of strings; each string is a label for a sequence of temperatures.
  zone_types=()
  zone_averages=()
  zone_indices=()

  # Enumerate zone_temps.
  for zone in thermal_zone*; do
    i="$(sed 's/^thermal_zone//' <<< "${zone}")"
    zone_temps["${i}"]=''
    zone_types["${i}"]="$(cat "${zone}/type")"
    zone_indices+=( "${i}" )
  done

  # Take temperature samples.
  for ti in {1..10}; do
    sleep "${interval}"
    for zi in "${zone_indices[@]}"; do
      zone="thermal_zone${zi}"
      zone_temps["${zi}"]="${zone_temps[${zi}]} $(cat "${zone}/temp")"
    done
  done

  # Take averages.
  for zi in "${zone_indices[@]}"; do
    read -a temps <<< "${zone_temps[${zi}]}"
    average=0
    unchanging=1
    temp_raw_old="${temps[0]}"
    for temp_raw in "${temps[@]}"; do
      if ! test "${temp_raw_old}" = "${temp_raw}"; then
        unchanging=0
      fi
      temp_raw_old="${temp_raw}"
      average=$(( average + temp_raw ))
    done
    average="$(bc <<< "scale=0; ${average} / ${#temps[@]} / 1000")"
    if test 1 = "${unchanging}"; then
      # Replace obviously fake data with fake data that won't alert.
      average="$(( warning_high - 1 ))"
    fi
    if test "${average}" -ge "${critical_high}"; then critical; fi
    if test "${average}" -le "${critical_low}"; then critical; fi
    if test "${average}" -ge "${warning_high}"; then warning; fi
    if test "${average}" -le "${warning_low}"; then warning; fi
    zone_averages["${zi}"]="${average}"
  done

  # Print the return value first.
  printf '%s ' "${ret}"

  # Print the remaining message second.
  for zi in "${zone_indices[@]}"; do
    printf 'Zone %s (%s):  %s°C;  ' "${zi}" "${zone_types[${zi}]}" "${zone_averages[${zi}]}"
  done
  printf '\n'

  # Return the appropriate value.
  return "${ret}"
}


function critical() {
  ret=2
}


function warning() {
  if test 2 = "${ret}"; then
    return 0
  else
    ret=1
  fi
}


main
